// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image3;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel1;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_lowbtn;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_higbtn;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_medbtn;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel3;
extern void ui_event_senS(lv_event_t * e);
extern lv_obj_t * ui_senS;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_senD;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

