// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image1;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Roller6;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label1;
extern void ui_event_Dropdown1(lv_event_t * e);
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label9;
extern void ui_event_Dropdown2(lv_event_t * e);
extern lv_obj_t * ui_Dropdown2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

