// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"

lv_obj_t * ui_Screen7 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Button12 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_pairL = NULL;
lv_obj_t * ui_Button13 = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_nPairedL = NULL;
lv_obj_t * ui_pairL1 = NULL;
// event funtions
void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        bindTXevt(e);
        _ui_flag_modify(ui_Panel10, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Spinner1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// build funtions

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image7, &ui_img_screen2_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button12 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_Button12, 68);
    lv_obj_set_height(ui_Button12, 15);
    lv_obj_set_x(ui_Button12, -105);
    lv_obj_set_y(ui_Button12, -107);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button12, 25, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label32 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 6);
    lv_obj_set_y(ui_Label32, -106);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "PAIR RECEIVER");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xFFCC31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Panel10, 148);
    lv_obj_set_height(ui_Panel10, 69);
    lv_obj_set_x(ui_Panel10, -9);
    lv_obj_set_y(ui_Panel10, -28);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x5C6D73), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pairL = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_pairL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pairL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pairL, 1);
    lv_obj_set_y(ui_pairL, -1);
    lv_obj_set_align(ui_pairL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pairL, "NOT PAIRED");
    lv_obj_set_style_text_color(ui_pairL, lv_color_hex(0xCDCBCA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pairL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pairL, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_Button13, 115);
    lv_obj_set_height(ui_Button13, 45);
    lv_obj_set_x(ui_Button13, -9);
    lv_obj_set_y(ui_Button13, 74);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0xFBC831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -1);
    lv_obj_set_y(ui_Label34, 2);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "PAIR NOW");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -7);
    lv_obj_set_y(ui_Label33, 27);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "Power receiver while \nholding bind button");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_Screen7, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 68);
    lv_obj_set_x(ui_Spinner1, -7);
    lv_obj_set_y(ui_Spinner1, -34);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xE6B41D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_nPairedL = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_nPairedL, 148);
    lv_obj_set_height(ui_nPairedL, 69);
    lv_obj_set_x(ui_nPairedL, -9);
    lv_obj_set_y(ui_nPairedL, -28);
    lv_obj_set_align(ui_nPairedL, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nPairedL, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_nPairedL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_nPairedL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_nPairedL, lv_color_hex(0x5C6D73), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nPairedL, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_nPairedL, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_nPairedL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_nPairedL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_nPairedL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pairL1 = lv_label_create(ui_nPairedL);
    lv_obj_set_width(ui_pairL1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pairL1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pairL1, 1);
    lv_obj_set_y(ui_pairL1, -1);
    lv_obj_set_align(ui_pairL1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pairL1, "PAIRED");
    lv_obj_set_style_text_color(ui_pairL1, lv_color_hex(0x1CF129), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pairL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pairL1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);

}

void ui_Screen7_screen_destroy(void)
{
    if(ui_Screen7) lv_obj_del(ui_Screen7);

    // NULL screen variables
    ui_Screen7 = NULL;
    ui_Image7 = NULL;
    ui_Button12 = NULL;
    ui_Label32 = NULL;
    ui_Panel10 = NULL;
    ui_pairL = NULL;
    ui_Button13 = NULL;
    ui_Label34 = NULL;
    ui_Label33 = NULL;
    ui_Spinner1 = NULL;
    ui_nPairedL = NULL;
    ui_pairL1 = NULL;

}
