// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Image4;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_signalStrL1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_powerL;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_idL;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

