// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image2;
extern void ui_event_profilesbtn(lv_event_t * e);
extern lv_obj_t * ui_profilesbtn;
extern void ui_event_settingsbtn(lv_event_t * e);
extern lv_obj_t * ui_settingsbtn;
extern void ui_event_linkbtn(lv_event_t * e);
extern lv_obj_t * ui_linkbtn;
extern void ui_event_statusbtn(lv_event_t * e);
extern lv_obj_t * ui_statusbtn;
extern void ui_event_calibratebtn(lv_event_t * e);
extern lv_obj_t * ui_calibratebtn;
extern lv_obj_t * ui_powerModeL;
extern lv_obj_t * ui_signalStrL;
extern lv_obj_t * ui_profileL;
extern lv_obj_t * ui_Label24;
// CUSTOM VARIABLES
extern lv_obj_t * uic_settingsbtn;
extern lv_obj_t * uic_linkbtn;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

