// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_lowbtn = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_higbtn = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_medbtn = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_senS = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_senD = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        encEvtCh(e);
    }
}

void ui_event_senS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        sensivityevt(e);
        _ui_slider_set_text_value(ui_senD, target, "", "");
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image3, &ui_img_screen2_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button2, 68);
    lv_obj_set_height(ui_Button2, 15);
    lv_obj_set_x(ui_Button2, -105);
    lv_obj_set_y(ui_Button2, -107);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button2, 25, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label5 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 6);
    lv_obj_set_y(ui_Label5, -106);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "SETTINGS");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFCC31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel1, 284);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, -5);
    lv_obj_set_y(ui_Panel1, -59);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x5C6D73), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Panel1);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 99);
    lv_obj_set_y(ui_Switch1, -2);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch1, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x11F58C), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x1B2527), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x20C72A), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Label10 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -65);
    lv_obj_set_y(ui_Label10, -5);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Encryption");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xF9F4F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel2, 284);
    lv_obj_set_height(ui_Panel2, 85);
    lv_obj_set_x(ui_Panel2, -4);
    lv_obj_set_y(ui_Panel2, 11);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x5C6D73), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lowbtn = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_lowbtn, 83);
    lv_obj_set_height(ui_lowbtn, 29);
    lv_obj_set_x(ui_lowbtn, -89);
    lv_obj_set_y(ui_lowbtn, 17);
    lv_obj_set_align(ui_lowbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lowbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lowbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lowbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lowbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lowbtn, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_lowbtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_lowbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_lowbtn, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label12 = lv_label_create(ui_lowbtn);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -4);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "LOW");
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -65);
    lv_obj_set_y(ui_Label11, -19);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "RF Power");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xF9F4F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_higbtn = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_higbtn, 83);
    lv_obj_set_height(ui_higbtn, 29);
    lv_obj_set_x(ui_higbtn, 93);
    lv_obj_set_y(ui_higbtn, 16);
    lv_obj_set_align(ui_higbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_higbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_higbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_higbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_higbtn, lv_color_hex(0xFDDA32), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_higbtn, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_higbtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_higbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_higbtn, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label13 = lv_label_create(ui_higbtn);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -4);
    lv_obj_set_y(ui_Label13, 0);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "HIGH");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_medbtn = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_medbtn, 83);
    lv_obj_set_height(ui_medbtn, 29);
    lv_obj_set_x(ui_medbtn, 1);
    lv_obj_set_y(ui_medbtn, 16);
    lv_obj_set_align(ui_medbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_medbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_medbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_medbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_medbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_medbtn, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_medbtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_medbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_medbtn, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label14 = lv_label_create(ui_medbtn);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -4);
    lv_obj_set_y(ui_Label14, 0);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "MED");
    lv_obj_set_style_text_align(ui_Label14, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel3, 284);
    lv_obj_set_height(ui_Panel3, 52);
    lv_obj_set_x(ui_Panel3, -2);
    lv_obj_set_y(ui_Panel3, 83);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x5C6D73), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_senS = lv_slider_create(ui_Panel3);
    lv_slider_set_value(ui_senS, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_senS) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_senS, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_senS, 150);
    lv_obj_set_height(ui_senS, 5);
    lv_obj_set_x(ui_senS, -42);
    lv_obj_set_y(ui_senS, 12);
    lv_obj_set_align(ui_senS, LV_ALIGN_CENTER);

    ui_Label15 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -76);
    lv_obj_set_y(ui_Label15, -11);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Sensitivity");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xF9F4F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_senD = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_senD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_senD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_senD, 68);
    lv_obj_set_y(ui_senD, 10);
    lv_obj_set_align(ui_senD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_senD, "20");
    lv_obj_set_style_text_color(ui_senD, lv_color_hex(0xF9F7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_senD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_senS, ui_event_senS, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lowbtn, lowPowerEvt, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(ui_medbtn, medPowerEvt, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(ui_higbtn, higPowerEvt, LV_EVENT_PRESSED, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Image3 = NULL;
    ui_Button2 = NULL;
    ui_Label5 = NULL;
    ui_Panel1 = NULL;
    ui_Switch1 = NULL;
    ui_Label10 = NULL;
    ui_Panel2 = NULL;
    ui_lowbtn = NULL;
    ui_Label12 = NULL;
    ui_Label11 = NULL;
    ui_higbtn = NULL;
    ui_Label13 = NULL;
    ui_medbtn = NULL;
    ui_Label14 = NULL;
    ui_Panel3 = NULL;
    ui_senS = NULL;
    ui_Label15 = NULL;
    ui_senD = NULL;

}
