// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"

lv_obj_t * uic_linkbtn;
lv_obj_t * uic_settingsbtn;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_profilesbtn = NULL;
lv_obj_t * ui_settingsbtn = NULL;
lv_obj_t * ui_linkbtn = NULL;
lv_obj_t * ui_statusbtn = NULL;
lv_obj_t * ui_calibratebtn = NULL;
lv_obj_t * ui_powerModeL = NULL;
lv_obj_t * ui_signalStrL = NULL;
lv_obj_t * ui_profileL = NULL;
lv_obj_t * ui_Label24 = NULL;
// event funtions
void ui_event_profilesbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_settingsbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_linkbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_statusbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_calibratebtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Screen5_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_calibration_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_profilesbtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_profilesbtn, 84);
    lv_obj_set_height(ui_profilesbtn, 60);
    lv_obj_set_x(ui_profilesbtn, -103);
    lv_obj_set_y(ui_profilesbtn, -44);
    lv_obj_set_align(ui_profilesbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_profilesbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_profilesbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_profilesbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_profilesbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_profilesbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_profilesbtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_profilesbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_profilesbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_profilesbtn, 25, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_settingsbtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_settingsbtn, 84);
    lv_obj_set_height(ui_settingsbtn, 60);
    lv_obj_set_x(ui_settingsbtn, 102);
    lv_obj_set_y(ui_settingsbtn, -43);
    lv_obj_set_align(ui_settingsbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settingsbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_settingsbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settingsbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_settingsbtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_settingsbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settingsbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_settingsbtn, 25, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_linkbtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_linkbtn, 58);
    lv_obj_set_height(ui_linkbtn, 90);
    lv_obj_set_x(ui_linkbtn, -2);
    lv_obj_set_y(ui_linkbtn, -8);
    lv_obj_set_align(ui_linkbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_linkbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_linkbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_linkbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_linkbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_linkbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_linkbtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_linkbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_linkbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_linkbtn, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_statusbtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_statusbtn, 84);
    lv_obj_set_height(ui_statusbtn, 60);
    lv_obj_set_x(ui_statusbtn, 102);
    lv_obj_set_y(ui_statusbtn, 36);
    lv_obj_set_align(ui_statusbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_statusbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_statusbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_statusbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statusbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_statusbtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_statusbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statusbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_statusbtn, 25, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_calibratebtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_calibratebtn, 84);
    lv_obj_set_height(ui_calibratebtn, 60);
    lv_obj_set_x(ui_calibratebtn, -102);
    lv_obj_set_y(ui_calibratebtn, 37);
    lv_obj_set_align(ui_calibratebtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_calibratebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_calibratebtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_calibratebtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_calibratebtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_calibratebtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_calibratebtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_calibratebtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_calibratebtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_calibratebtn, 25, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_powerModeL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_powerModeL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerModeL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powerModeL, -92);
    lv_obj_set_y(ui_powerModeL, 103);
    lv_obj_set_align(ui_powerModeL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powerModeL, "HIGH");
    lv_obj_set_style_text_color(ui_powerModeL, lv_color_hex(0x5CE1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powerModeL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_powerModeL, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_signalStrL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_signalStrL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_signalStrL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_signalStrL, 111);
    lv_obj_set_y(ui_signalStrL, 105);
    lv_obj_set_align(ui_signalStrL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_signalStrL, "-45 ");
    lv_obj_set_style_text_color(ui_signalStrL, lv_color_hex(0x5CE1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_signalStrL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_signalStrL, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_profileL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_profileL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profileL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_profileL, 7);
    lv_obj_set_y(ui_profileL, 103);
    lv_obj_set_align(ui_profileL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_profileL, "RC PLANE");
    lv_obj_set_style_text_color(ui_profileL, lv_color_hex(0x5CE1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_profileL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_profileL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 137);
    lv_obj_set_y(ui_Label24, 105);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "dBm");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x5CE1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_profilesbtn, ui_event_profilesbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsbtn, ui_event_settingsbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_linkbtn, ui_event_linkbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_statusbtn, ui_event_statusbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_calibratebtn, ui_event_calibratebtn, LV_EVENT_ALL, NULL);
    uic_settingsbtn = ui_settingsbtn;
    uic_linkbtn = ui_linkbtn;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image2 = NULL;
    ui_profilesbtn = NULL;
    uic_settingsbtn = NULL;
    ui_settingsbtn = NULL;
    uic_linkbtn = NULL;
    ui_linkbtn = NULL;
    ui_statusbtn = NULL;
    ui_calibratebtn = NULL;
    ui_powerModeL = NULL;
    ui_signalStrL = NULL;
    ui_profileL = NULL;
    ui_Label24 = NULL;

}
